{{- if .Values.metrics.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-dir.fullname" . }}-metrics
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  labels:
    {{- include "helm-dir.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  {{- if not .Values.metrics.autoscaling.enabled }}
  replicas: {{ .Values.metrics.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-dir.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: metrics
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-dir.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: metrics
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-dir.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: metrics
        image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        ports:
        - containerPort: {{ .Values.metrics.service.targetPort }}
          name: http
          protocol: TCP
        - containerPort: 3001
          name: metrics
          protocol: TCP
        {{- with .Values.metrics.probes.liveness }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.metrics.probes.readiness }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        resources:
          {{- toYaml .Values.metrics.resources | nindent 12 }}
        {{- with .Values.volumeMounts }}
        volumeMounts:
          {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.metrics.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
